trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'
  
- script: |
    CI=true npm test
  displayName: 'Run tests'

- script: |
    CI=true npm run build
  displayName: 'Build application'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'tuananh2401/my-app'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'dockerhub-connection'
    tags: |
      latest
      $(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- script: |
    curl -X POST -H "Authorization: Bearer $(VercelToken)" https://api.vercel.com/v1/integrations/deploy/prj_M0n6kkZleOgqfNpGwE75B6IJRWl7/IgxDWpx6TR
  displayName: 'Trigger Vercel Deploy'
  env:
    VercelToken: $(VercelToken)
