trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'
  
- script: |
    npm run build
  displayName: 'Build application'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'tuananh2401/my-app'
    dockerfile: './Dockerfile'
    containerRegistry: 'dockerhub-connection'
    tags: |
      latest
      $(Build.BuildId)
  displayName: 'Build and Push Docker Image'
