trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'
  
- task: Docker@2
  inputs:
    command: 'build'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'dockerhub-connection'
    repository: 'tuananh2401/my-app'
    tags: |
      $(Build.BuildId)
  displayName: 'Build Docker Image'

- task: Docker@2
  inputs:
    command: 'push'
    containerRegistry: 'dockerhub-connection'
    repository: 'tuananh2401/my-app'
    tags: |
      $(Build.BuildId)
  displayName: 'Push Docker Image to Docker Hub'

- script: |
    curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_M0n6kkZleOgqfNpGwE75B6IJRWl7/IgxDWpx6TR
  displayName: 'Trigger Vercel Deploy'
