trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@1
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'dockerhub-connection'
    repository: 'tuananh2401/my-app'
    tags: |
      $(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- script: |
    curl -X POST -H "Authorization: Bearer $(VercelToken)" https://api.vercel.com/v1/integrations/deploy/prj_M0n6kkZleOgqfNpGwE75B6IJRWl7/IgxDWpx6TR
  displayName: 'Trigger Vercel Deploy'
  env:
    VercelToken: $(VercelToken)
